import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('netflix_titles.csv')
print("FIRST 5 ROWS")
print(df.head())
print("\nDATASET INFO")
print(df.info())
print("\nMISSING VALUES")
print(df.isnull().sum())
df['country'].fillna('Unknown', inplace=True)
df['director'].fillna('Unknown', inplace=True)
df['cast'].fillna('Unknown', inplace=True)
print("\nBASIC STATISTICS")
print(df.describe(include='all'))
plt.figure(figsize=(6,4))
sns.countplot(x='type', data=df, palette='Set2')
plt.title('Count of Movies vs TV Shows')
plt.xlabel('Type')
plt.ylabel('Count')
plt.show()
plt.figure(figsize=(10,5))
df['country'].value_counts().head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 Countries with Most Content on Netflix')
plt.xlabel('Country')
plt.ylabel('Count')
plt.show()
plt.figure(figsize=(10,5))
df['release_year'].value_counts().sort_index(ascending=True).plot(kind='line', color='red')
plt.title('Content Added Over the Years')
plt.xlabel('Release Year')
plt.ylabel('Number of Titles')
plt.show()
plt.figure(figsize=(8,5))
df['rating'].value_counts().head(10).plot(kind='bar', color='orange')
plt.title('Top 10 Ratings on Netflix')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()
plt.figure(figsize=(10,6))
top_genres = df['listed_in'].value_counts().head(10)
sns.barplot(y=top_genres.index, x=top_genres.values, palette='viridis')
plt.title('Top 10 Genres on Netflix')
plt.xlabel('Count')
plt.ylabel('Genre')
plt.show()
